name: 'Tag action'
description: 'Action to tag commits based on previous tags on the repository'
author: 'Lucas Ferreira'
inputs:
  build_number:  # id of input
    description: 'Build number to be appended on the tag'
    required: false
    default: ''
outputs:
  tag: # id of output
    description: 'the tag generated'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.build_number }}
branding:
    icon: 'tag'  
    color: 'yellow'
      
